name: Dev to Main CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install
          npm start &

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Run unit tests for frontend
        run: |
          cd frontend
          npm test

      - name: Run unit tests for backend
        run: |
          cd backend
          npm test

      - name: Run end-to-end tests
        run: |
          cd e2e-tests
          npm install
          npm test

      - name: Build and push Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          
          docker build -t $DOCKER_USERNAME/reverse-todo-list:backend-latest ./backend
          
          docker build -t $DOCKER_USERNAME/reverse-todo-list:frontend-latest ./frontend
          
          docker push $DOCKER_USERNAME/reverse-todo-list:backend-latest
          
          docker push $DOCKER_USERNAME/reverse-todo-list:frontend-latest